- name: Install Node.js prereqs
  action: apt pkg={{ item }} state=installed
  with_items:
    - build-essential
    - checkinstall
    - libssl-dev
- name: Import the NodeSource GPG key into apt
  apt_key:
    url: "{{ node_source_key_url }}"
    state: present
- name: Add NodeSource deb repository
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ node_version }} {{ ubuntu_dist }} main"
    state: present
- name: Add NodeSource deb-src repository
  apt_repository:
    repo: "deb-src https://deb.nodesource.com/node_{{ node_version }} {{ ubuntu_dist }} main"
    state: present
- name: Install Node.js
  apt:
    pkg: nodejs
    state: present
    update_cache: yes
